### PR TITLE
Improve build: installed rocks, build URL(s)

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by psychon** [comment]
Same comment as in the PR in the Awesome repository: I don't understand the need nor effect for/of the call to `column`. Besides that :+1:

**Comment by blueyed** [comment]
`column` aligns the output, just looks better / easier to parse with eyes.

**Comment by psychon** [comment]
Well... https://github.com/awesomeWM/awesome/pull/2704#issuecomment-466996260

**Comment by blueyed** [comment]
Oh snap - typo: I've meant `\t` instead of `\r`.
Fixed in 842e315.

**Pull request merged**
