### PR TITLE
Add a README

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by psychon** [comment]
:+1:

**Comment by psychon** [comment]
However: Doesn't this mean the README also ends up in the built wiki? Perhaps the Makefile should prevent that.

**Comment by blueyed** [comment]
> Doesn't this mean the README also ends up in the built wiki? Perhaps the Makefile should prevent that.

Probably.  I'll look into it.

**Comment by blueyed** [comment]
Closing this in favor of https://github.com/awesomeWM/awesome-www/pull/21 - which has the exlude (and will have a pr-preview branch).

**Pull request closed without merging**
