### PR TITLE
New screenshot

### PR DESCRIPTION
**Pull request by Elv13**
@blueyed and me think this is a better screenshot for the front page:

 * it isn't 7 years old
 * it is close enough to the stock theme, but nicer
 * it uses icons and useless gap
 * the default theme is dated
 * it proves that Awesome can look modern if you invest some time into it

@folcraed Thanks!

### CODE REVIEW

**Comment by folcraed** [comment]
You're very welcome! Really, thank you all for keeping Awesome moving forward. I'm just a very happy user.

**Comment by Elv13** [comment]
@folcraed also proposed http://imgur.com/I7eL5it

img

Both are nice, I guess we have to pick one of the two

**Comment by folcraed** [comment]
If you would like something else, please ask. Something showing the windows more "traditionally" floating... with the compositor off... different gaps... whatever you think would look better.

**Comment by psychon** [comment]
I also agree. So, since everyone agrees...

**Pull request merged**
