### PR TITLE
Add a doing_a_release page

### PR DESCRIPTION
**Pull request by psychon**
This page is described on the old document that was available on the
wiki. However, I updated it to the new state of things and, for example,
left out the mailing list. This means that lots of the things here are
new and untested, but I guess they will be tested soon.

Signed-off-by: Uli Schlachter <psychon@znc.in>

That's it with my time for today. Sorry, but your Christmas present will have to wait until tomorrow (but only if you are good and merge all my pull requests ;-) ).

Of course, feel free to point out possible improvements before I do something wrong!

### CODE REVIEW

**Comment by psychon** [comment]
Oh, one thing that just came to my mind:

Should it be verified somehow that Travis can build the docs before a release is done? If one just follows the instructions that I am proposing here, a failure on Travis will only be notice at the end of the instructions when everything else is already done, meaning people might be in a hurry and rush things to fix Travis for awesome-www.
So, should a build of the web page should first be attempted on a branch before continuing with the rest of the release?

**Comment by blueyed** [comment]
> So, should a build of the web page should first be attempted on a branch before continuing with the rest of the release?

Going through a PR would be good, but requires to push the tag before already, which might be fine?!

**Comment by psychon** [comment]
> Going through a PR would be good, but requires to push the tag before already, which might be fine?!

Pushed a fixup commit. How is the result?

**Comment by blueyed** [comment]
Seems to make sense.
The release branch should not be squash-merged then though I assume?! (otherwise the commit hash will change / go away)

**Comment by psychon** [comment]
The branch only has one commit anyway, there is not much to squash...? However, why would it be a problem? The only commit id which may not change is the tagged release, because `awesome-www` uses it (and because modifying tags is evil).

**Comment by blueyed** [comment]
Oh, I've initially thought to create the `release` branch on the `awesome` repo..

It is fine then.. in case the PR turns out to break (and it's because of `awesome`), then a new release tag would have to be created, right?

**Comment by psychon** [comment]
I thought the build of the web page would fail because of missing dependencies on Travis. If there are other kinds of problems with the release, they should be caught before we decide to do a release.

**Comment by psychon** [comment]
Squashed. Will merge once Travis is green.

**Pull request merged**
