### PR TITLE
ikiwiki: --url is not required, since we are not using --rss / blogs

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/awesomeWM/awesome-www/pull/12#issuecomment-219466960.

### CODE REVIEW

**Comment by psychon** [comment]
Could you grep the generated HTML for references to this URL? If nothing is found (or nothing interesting is found), feel free to merge.

**Comment by blueyed** [comment]
Yes, there's nothing in https://github.com/awesomeWM/awesomeWM.github.io/compare/pr-17.diff.

**Comment by Elv13** [comment]
Are you really sure about that `ikiwiki` choice? Is this a final decision? I am still unconvinced having 2 different wiki solutions in parallel is a good idea.

**Comment by psychon** [comment]
Well, ikiwiki is already the current web page, so think of this more as "the current web page" and not "a wiki". Also `ldoc` doesn't count as a wiki for me.
So if your argument is "ldoc is already a wiki, we don't need ikiwiki", then I disagree (on both points).

I'm pretty much out of things I want to save from the current wiki, so I'm done.

What about you? Where do you want to link to things like tyranical?
(Avoiding the word wiki:) I don't think mentioning tyranical or other external libraries belongs into the API doc. That only leaves the web page for that.

**Pull request merged**
