### PR TITLE
chore: switch from travis to gh actions (fixes #169)

### LINKED ISSUE #169: oh wow when we moved from travis to GH actions we forgot about this one 😅

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by Elv13** [comment]
Huge thanks for this. Do you want to merge that already and iterate with new PRs for the fixes or want to play whack a mole for a few iterations?

**Comment by aajjbb** [comment]
Should this also include a change in README.md to remove the travis reference?

**Comment by Elv13** [comment]
The issue is more that Travis removed itself. They switched off all open source projects free accounts once they consumed some "credits". I paid for the commercial version for 6months until amazing people helped to move the main repo to GitHub actions. I knew when I stopped paying it would break the  `-www` repo, but it wasn't worth paying 1000$US a year for this repo alone.

**Comment by actionless** [comment]
i think it's ready now

**Comment by actionless** [comment]
now gon be the most interesting part 😹

**Comment by actionless** [comment]
apparently it needs token to be set in secrets?

https://github.com/awesomeWM/awesome-www/runs/7063206869?check_suite_focus=true#step:14:692

**Comment by actionless** [comment]
and also it doesn't show the commit range correctly🙁 : https://github.com/awesomeWM/awesome-www/runs/7063206869?check_suite_focus=true#step:14:35

**Comment by Elv13** [comment]
I gave you the rights to manage the secrets for `-www`, you should be able to set them now

**Comment by actionless** [comment]
no, i don't (neither for /awesome/ repo itself)

**Comment by Elv13** [comment]
you really should. Maybe it sent you an email with an invite link?

image

**Comment by Elv13** [comment]
Anyway, if for whatever reason its broken, give me instructions and I will try to set them.

**Comment by actionless** [comment]
now i can see the secrets for www repo, but not for the main one

i need to copy the same secret from https://github.com/awesomeWM/awesome/settings/secrets/actions to https://github.com/awesomeWM/awesome-www/settings/secrets/actions

**Comment by actionless** [comment]
(i guess key itself should be somewhere in the settings of this repo, but i can't view them neither: https://github.com/awesomeWM/awesomeWM.github.io)

**Comment by Elv13** [comment]
The `AWESOME_ROBOT_TOKEN` secret?

**Comment by actionless** [comment]
yup

**Comment by actionless** [comment]
the key i think should be at https://github.com/awesomeWM/awesomeWM.github.io/settings/keys

**Comment by Elv13** [comment]
@blueyed Can you add it to `-www`. I can change it, but I can't view it.

**Comment by actionless** [comment]
i think you can just add a new key there as well if you can't view existing one: https://github.com/awesomeWM/awesomeWM.github.io/settings/keys

**Comment by Elv13** [comment]
I think it in a normal github account, not the project one ( https://github.com/awesome-robot ). I don't control that account. Let's wait a couple days and see if Daniel replies.

**Comment by actionless** [comment]
no, i mean you can use just a deployment key frmo there: https://github.com/awesomeWM/awesomeWM.github.io/settings/keys

**Comment by actionless** [comment]
(with write access)

**Comment by Elv13** [comment]
Right now there isn't any. I am pretty sure it was just using the robot account so far. Is it worth changing that?

**Comment by actionless** [comment]
i think it shouldn't be much difference - as you sharing that token only with github, not with some additional third-parties like travis

**Comment by Elv13** [comment]
Ok, go ahead, I made you admin

**Comment by actionless** [comment]
my bad, i tried - it allowing to generate only ssh key but not the token :(

**Comment by actionless** [comment]
i could generate a token from my own account in order just to test all ci step work

**Comment by actionless** [comment]
(and after testing remove the token and wait next for @blueyed to upt the correct token instead of it)

**Comment by Elv13** [comment]
As a temporary solution maybe. Long term we need to find a way to manage the robot account in a way that doesn't involve a single point of failure.

But right now, getting -www to work again is worth a few hacks. It being broken is a rather big problem and I am glad you are taking upon fixing that, so go ahead.

**Comment by actionless** [comment]
now it works

also somebody would need to set:           $CLOUDFLARE_ZONE $CLOUDFLARE_AUTH_EMAIL $CLOUDFLARE_AUTH_KEY

**Pull request merged**
