### PR TITLE
Use https for flattr and ohloh/openhub widgets; update them

### PR DESCRIPTION
**Pull request by blueyed**
See https://www.openhub.net/p/awesome/widgets for a list of available openhub widgets.

Without this the widgets are not loaded on https://awesomewm.org.

### CODE REVIEW

**Comment by psychon** [comment]
Merged, but I'm too lazy to rebuild the web page right now... Looking forward to using Travis for this.

**Comment by blueyed** [comment]
> Looking forward to using Travis for this

Do you want to give it a try, or should I look into this?

**Comment by psychon** [comment]
I tried to do this with `sudo: false` and didn't have much success:
- https://github.com/psychon/awesome-www/blob/travis/.travis.yml
- https://travis-ci.org/psychon/awesome-www/builds/128680430
- https://travis-ci.org/psychon/awesome-www/builds/124116511 (same as the `.travis.yml` above, but without `addons.apt.sources: debian-sid`).
At this point I gave up since I thought that having travis rebuild all dependencies is stupid. Can't they just use something else than Ubuntu Ancient? :-(

Note that due to the API doc, building the web page requires all of awesome's build deps.

**Comment by blueyed** [comment]
> Note that due to the API doc, building the web page requires all of awesome's build deps.

The API doc could still be built from the main repo, couldn't it?

**Comment by psychon** [comment]
At least that's not how it's done currently. ;-)
This would need a new way to get the doc onto the web page. I think currently only the docs for master are available online via gh-pages. My plan was to keep it this way so that building awesome-www is self-contained, but feel to come up with something new.

**Comment by blueyed** [comment]
> This would need a new way to get the doc onto the web page. I think currently only the docs for master are available online via gh-pages. 

It could be done from the 3.5 Travis branch also, e.g. master would be available at http://awesomewm.github.io/apidoc/ and stable at some other address.

Do I understand it correctly that http://awesomewm.github.io/ is served from https://github.com/awesomeWM/awesomeWM.github.io, but http://awesomewm.github.io/apidoc/ comes from the apidoc's gh-pages branch still?
Then we could have a new apidoc-stable repo.

Having builds of awesome-www being self-contained sounds good though.  Couldn't we link to / re-use the existing `.travis.yml` file from the `src` submodule then?  (mangled through a Makefile)

**Comment by psychon** [comment]
Yup, you understand the naming of the Git repos correctly.

On using the existing `.travis.yml`:
Most of its contents aren't needed and apparently we would just need to build `lua-ldoc` (which is just an installation of `luarocks` away, I guess (already available in Ubuntu!)) and `libxcb-cursor-dev` ourselves, for the rest we could use the package from Ubuntu.
Without having really tried it, it feels to me like the `.travis.yml` for `awesome-www` could be a lot simpler.

**Comment by blueyed** [comment]
The error from the first try with Debian:

> Unpacking replacement locales ...
> dpkg: error processing /var/cache/apt/archives/locales_2.22-7_all.deb (--unpack):
>  trying to overwrite '/usr/sbin/validlocale', which is also in package libc-bin 2.15-0ubuntu10.13

Maybe that can be forced somehow.. there are options to dpkg to do so.. and/or upgrading libc-bin before might avoid this altogether?
Try doing this from a `before_install` hook maybe?! (https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-from-a-custom-APT-repository)

**Comment by psychon** [comment]
Here's a working travis file (but of course it fails to upload the docs to naquadah.org):
- https://github.com/psychon/awesome-www/blob/travis/.travis.yml
- https://travis-ci.org/psychon/awesome-www/builds/130523233

I guess this now just needs to be changed so that it doesn't upload to naquadah.org, but to https://github.com/awesomeWM/awesomeWM.github.io (master branch!). @blueyed Do you want to handle this part? You are our `GH_TOKEN` juggler.

**Comment by blueyed** [comment]
@psychon 
I'll look into it.
So the "push" Makefile target needs to be replaced, right?
I would then just do "make push" in the Travis' `script` part?

**Comment by psychon** [comment]
Yup. Right now `make push` uses rsync to upload the resulting webpage. I used this in my travis file as the target because it has the right dependencies and no other target has them.

**Pull request merged**
