### PR TITLE
Update recipes.mdwn

### PR DESCRIPTION
**Pull request by streetturtle**
Add link to the github repo with widgets for Awesome WM

### CODE REVIEW

**Comment by psychon** [comment]
Could you be a bit more specific? For example:
```
* [Set of simple widgets](https://github.com/streetturtle/awesome-wm-widgets) - Widgets for battery,
   brightness, cpu, email, rhythmbox, spotify, volume, and weather.

**Comment by streetturtle** [comment]
Is it ok like this? I'd like to add more widgets in the future and with such description I won't need to update it with every new widget.

**Comment by streetturtle** [comment]
Should I squash the commit?

**Comment by Elv13** [comment]
@streetturtle Sorry, it slit in the cracks, I (we?) just forgot to merge it.

**Pull request merged**
