### PR TITLE
Making standout more compliant with the new design.

### PR DESCRIPTION
**Pull request by aajjbb**

### CODE REVIEW

**Comment by psychon** [comment]
Isn't it inconsistent if links sometimes are blue+underlined and sometimes just red?

**Comment by aajjbb** [comment]
The links are red only in pieces covered by the `standout` class. As we want this section to be such kind of _warning_, the light blue link doesn't call much attention.

**Comment by blueyed** [comment]
Would be nice to have a bot that creates some preview somewhere for PRs.. ^^

**Comment by aajjbb** [comment]
Here's a preview. There's no much changes, it's just to call more attention to the migration link. 

The bot would be great.
2017-01-24-17-59-49_1920x1080

**Comment by blueyed** [comment]
What @Elv13 had in mind was probably to have everything / the sentence in red.
I'm still 👍.

**Comment by aajjbb** [comment]
So, my first idea was to have everything under `standout` in red, but I couldn't find a proper color for links, so I ended up letting the links red;

**Comment by actionless** [comment]
but why not to underline red links as well?

**Comment by aajjbb** [comment]
Trying a new perspective, the colors are a little 'softer'. The plain html 'red' is too much _strong_ for the site colors. 
2017-01-24-19-08-09_1920x1080

**Comment by blueyed** [comment]
I'm also for keeping the link style unchanged (i.e. to remove the `text-decoration: none;`).

The new colors are a bit weird IMHO.

I'd vote for removing the css changes from this PR, but keep the rest.

**Comment by aajjbb** [comment]
I actually liked @actionless color suggestion, here is a screenshot. 
2017-01-24-20-56-29_1366x768

**Comment by blueyed** [comment]
LGTM!

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
