### PR TITLE
Adding a recipes section

### PR DESCRIPTION
**Pull request by aajjbb**
Hi, the goal of this new recipes section is to be a home for the ones who miss the wiki. The goal here is to post config files, different widgets and other awesome related stuff (similarly with the old wiki, but better organized, as new content is received as pull requests).

### CODE REVIEW

**Comment by blueyed** [comment]
Makes sense.

I still feel like we should reconsider more advanced tools like Sphinx if we expand the doc in many more directions.
(But it is also easier for PRs to just have markdown by itself maybe?!)

**Comment by aajjbb** [comment]
I think it wouldn't be a doc expansion per se. It would be more of a collaborative comprehensive list of things related with awesome. Do you have an use case for a more advanced tool ?

**Comment by blueyed** [comment]
Not yet, but the current approach is basically just a list.

But we could always add headings/sections later - that's what I've been thinking about mainly.

**Comment by aajjbb** [comment]
Should it be added in this PR or in a separated one ?

**Comment by psychon** [comment]
Doesn't matter to me. Either one is fine with me. I'll let others decide. @blueyed ?

**Comment by blueyed** [comment]
> we should also add a prominent hint on this page on how to modify/extend it
> We already have that on the Community page, I think, but that is easily missed.

Maybe the "fork me" button from the new design helps here already?!
Have not checked if it can be made to just edit the current page somehow?!

**Comment by blueyed** [comment]
I am merging this for now, but either let's keep discussing it here, or please create a new issue/PR to track this, @aajjbb.

**Pull request merged**
