### PR TITLE
Add Pulseaudio, Connman and Battery to Widgets recipes

### PR DESCRIPTION
**Pull request by stefano-m**
@psychon suggested in https://github.com/stefano-m/awesome-pulseaudio_widget/issues/1#issue-241511660 that I add my PulseAudio widget to the recipes page.

I have also added two more widgets written by me: Connman network manager and Battery Indicator (uses UPower).

All widgets are available from [my luarocks.org modules](http://luarocks.org/modules/stefano-m) too.

### CODE REVIEW

**Comment by aajjbb** [comment]
Welcome to the recipes section :+1:

**Comment by blueyed** [comment]
Thank you!
I've found https://github.com/stefano-m/awesome-pulseaudio_widget myself recently, and still have to try it out.

**Comment by stefano-m** [comment]
Thanks! Looking forward to your feedback.

**Comment by blueyed** [comment]
@stefano-m 
1. It would be easier to install from a checkout if there was an `init.lua` file/symlink (https://github.com/stefano-m/awesome-pulseaudio_widget/issues/2).
2. I've installed `pulseaudio` via `luarocks install --local`, but then it is not available in Awesome by default (https://github.com/awesomeWM/awesome/pull/1860#issuecomment-315564464).

I guess I could execute `eval $(luarocks path)` before awesome itself maybe?!

**Pull request merged**
